<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.FolderShare</code>
 */
class FolderShare extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    private $path = '';
    /**
     * Generated from protobuf field <code>string owner_id = 3;</code>
     */
    private $owner_id = '';
    /**
     * Generated from protobuf field <code>string recipient_id = 4;</code>
     */
    private $recipient_id = '';
    /**
     * Generated from protobuf field <code>bool read_only = 5;</code>
     */
    private $read_only = false;
    /**
     * Generated from protobuf field <code>uint64 ctime = 7;</code>
     */
    private $ctime = 0;
    /**
     * Generated from protobuf field <code>uint64 mtime = 8;</code>
     */
    private $mtime = 0;

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 3;</code>
     * @return string
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string recipient_id = 4;</code>
     * @return string
     */
    public function getRecipientId()
    {
        return $this->recipient_id;
    }

    /**
     * Generated from protobuf field <code>string recipient_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRecipientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->recipient_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 5;</code>
     * @return bool
     */
    public function getReadOnly()
    {
        return $this->read_only;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setReadOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->read_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ctime = 7;</code>
     * @return int|string
     */
    public function getCtime()
    {
        return $this->ctime;
    }

    /**
     * Generated from protobuf field <code>uint64 ctime = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtime($var)
    {
        GPBUtil::checkUint64($var);
        $this->ctime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 mtime = 8;</code>
     * @return int|string
     */
    public function getMtime()
    {
        return $this->mtime;
    }

    /**
     * Generated from protobuf field <code>uint64 mtime = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMtime($var)
    {
        GPBUtil::checkUint64($var);
        $this->mtime = $var;

        return $this;
    }

}

