<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.LinkPermissions</code>
 */
class LinkPermissions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool read = 1;</code>
     */
    private $read = false;
    /**
     * Generated from protobuf field <code>bool write = 2;</code>
     */
    private $write = false;

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool read = 1;</code>
     * @return bool
     */
    public function getRead()
    {
        return $this->read;
    }

    /**
     * Generated from protobuf field <code>bool read = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setRead($var)
    {
        GPBUtil::checkBool($var);
        $this->read = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool write = 2;</code>
     * @return bool
     */
    public function getWrite()
    {
        return $this->write;
    }

    /**
     * Generated from protobuf field <code>bool write = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setWrite($var)
    {
        GPBUtil::checkBool($var);
        $this->write = $var;

        return $this;
    }

}

