<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.Metadata</code>
 */
class Metadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    private $path = '';
    /**
     * Generated from protobuf field <code>uint64 size = 3;</code>
     */
    private $size = 0;
    /**
     * Generated from protobuf field <code>uint64 mtime = 4;</code>
     */
    private $mtime = 0;
    /**
     * Generated from protobuf field <code>bool is_dir = 5;</code>
     */
    private $is_dir = false;
    /**
     * Generated from protobuf field <code>string etag = 6;</code>
     */
    private $etag = '';
    /**
     * Generated from protobuf field <code>string checksum = 7;</code>
     */
    private $checksum = '';
    /**
     * Generated from protobuf field <code>string deref_path = 8;</code>
     */
    private $deref_path = '';

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 3;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 mtime = 4;</code>
     * @return int|string
     */
    public function getMtime()
    {
        return $this->mtime;
    }

    /**
     * Generated from protobuf field <code>uint64 mtime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMtime($var)
    {
        GPBUtil::checkUint64($var);
        $this->mtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_dir = 5;</code>
     * @return bool
     */
    public function getIsDir()
    {
        return $this->is_dir;
    }

    /**
     * Generated from protobuf field <code>bool is_dir = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDir($var)
    {
        GPBUtil::checkBool($var);
        $this->is_dir = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string etag = 6;</code>
     * @return string
     */
    public function getEtag()
    {
        return $this->etag;
    }

    /**
     * Generated from protobuf field <code>string etag = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setEtag($var)
    {
        GPBUtil::checkString($var, True);
        $this->etag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string checksum = 7;</code>
     * @return string
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * Generated from protobuf field <code>string checksum = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setChecksum($var)
    {
        GPBUtil::checkString($var, True);
        $this->checksum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deref_path = 8;</code>
     * @return string
     */
    public function getDerefPath()
    {
        return $this->deref_path;
    }

    /**
     * Generated from protobuf field <code>string deref_path = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDerefPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->deref_path = $var;

        return $this;
    }

}

