<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.MoveReq</code>
 */
class MoveReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string old_path = 1;</code>
     */
    private $old_path = '';
    /**
     * Generated from protobuf field <code>string new_path = 2;</code>
     */
    private $new_path = '';

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string old_path = 1;</code>
     * @return string
     */
    public function getOldPath()
    {
        return $this->old_path;
    }

    /**
     * Generated from protobuf field <code>string old_path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOldPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->old_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string new_path = 2;</code>
     * @return string
     */
    public function getNewPath()
    {
        return $this->new_path;
    }

    /**
     * Generated from protobuf field <code>string new_path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNewPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->new_path = $var;

        return $this;
    }

}

