<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.NewLinkReq</code>
 */
class NewLinkReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string path = 1;</code>
     */
    private $path = '';
    /**
     * Generated from protobuf field <code>bool read_only = 2;</code>
     */
    private $read_only = false;
    /**
     * Generated from protobuf field <code>string password = 3;</code>
     */
    private $password = '';
    /**
     * Generated from protobuf field <code>uint64 expires = 4;</code>
     */
    private $expires = 0;

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 2;</code>
     * @return bool
     */
    public function getReadOnly()
    {
        return $this->read_only;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setReadOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->read_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expires = 4;</code>
     * @return int|string
     */
    public function getExpires()
    {
        return $this->expires;
    }

    /**
     * Generated from protobuf field <code>uint64 expires = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpires($var)
    {
        GPBUtil::checkUint64($var);
        $this->expires = $var;

        return $this;
    }

}

