<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.PublicLink</code>
 */
class PublicLink extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token = 1;</code>
     */
    private $token = '';
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    private $path = '';
    /**
     * Generated from protobuf field <code>bool protected = 3;</code>
     */
    private $protected = false;
    /**
     * Generated from protobuf field <code>uint64 expires = 5;</code>
     */
    private $expires = 0;
    /**
     * Generated from protobuf field <code>bool read_only = 6;</code>
     */
    private $read_only = false;
    /**
     * Generated from protobuf field <code>uint64 mtime = 8;</code>
     */
    private $mtime = 0;

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool protected = 3;</code>
     * @return bool
     */
    public function getProtected()
    {
        return $this->protected;
    }

    /**
     * Generated from protobuf field <code>bool protected = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setProtected($var)
    {
        GPBUtil::checkBool($var);
        $this->protected = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expires = 5;</code>
     * @return int|string
     */
    public function getExpires()
    {
        return $this->expires;
    }

    /**
     * Generated from protobuf field <code>uint64 expires = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpires($var)
    {
        GPBUtil::checkUint64($var);
        $this->expires = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 6;</code>
     * @return bool
     */
    public function getReadOnly()
    {
        return $this->read_only;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setReadOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->read_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 mtime = 8;</code>
     * @return int|string
     */
    public function getMtime()
    {
        return $this->mtime;
    }

    /**
     * Generated from protobuf field <code>uint64 mtime = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMtime($var)
    {
        GPBUtil::checkUint64($var);
        $this->mtime = $var;

        return $this;
    }

}

