<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.RecycleEntryResponse</code>
 */
class RecycleEntryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.api.StatusCode status = 1;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>.api.RecycleEntry recycleEntry = 2;</code>
     */
    private $recycleEntry = null;

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.api.StatusCode status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.api.StatusCode status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Api\StatusCode::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.api.RecycleEntry recycleEntry = 2;</code>
     * @return \Api\RecycleEntry
     */
    public function getRecycleEntry()
    {
        return $this->recycleEntry;
    }

    /**
     * Generated from protobuf field <code>.api.RecycleEntry recycleEntry = 2;</code>
     * @param \Api\RecycleEntry $var
     * @return $this
     */
    public function setRecycleEntry($var)
    {
        GPBUtil::checkMessage($var, \Api\RecycleEntry::class);
        $this->recycleEntry = $var;

        return $this;
    }

}

