<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.RecycleEntry</code>
 */
class RecycleEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string restore_path = 1;</code>
     */
    private $restore_path = '';
    /**
     * Generated from protobuf field <code>string restore_key = 2;</code>
     */
    private $restore_key = '';
    /**
     * Generated from protobuf field <code>uint64 size = 3;</code>
     */
    private $size = 0;
    /**
     * Generated from protobuf field <code>uint64 del_mtime = 4;</code>
     */
    private $del_mtime = 0;
    /**
     * Generated from protobuf field <code>bool is_dir = 5;</code>
     */
    private $is_dir = false;

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string restore_path = 1;</code>
     * @return string
     */
    public function getRestorePath()
    {
        return $this->restore_path;
    }

    /**
     * Generated from protobuf field <code>string restore_path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRestorePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->restore_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string restore_key = 2;</code>
     * @return string
     */
    public function getRestoreKey()
    {
        return $this->restore_key;
    }

    /**
     * Generated from protobuf field <code>string restore_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRestoreKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->restore_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 3;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 del_mtime = 4;</code>
     * @return int|string
     */
    public function getDelMtime()
    {
        return $this->del_mtime;
    }

    /**
     * Generated from protobuf field <code>uint64 del_mtime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelMtime($var)
    {
        GPBUtil::checkUint64($var);
        $this->del_mtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_dir = 5;</code>
     * @return bool
     */
    public function getIsDir()
    {
        return $this->is_dir;
    }

    /**
     * Generated from protobuf field <code>bool is_dir = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDir($var)
    {
        GPBUtil::checkBool($var);
        $this->is_dir = $var;

        return $this;
    }

}

