<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

/**
 * Protobuf enum <code>Api\StatusCode</code>
 */
class StatusCode
{
    /**
     * Generated from protobuf enum <code>OK = 0;</code>
     */
    const OK = 0;
    /**
     * Generated from protobuf enum <code>UNKNOWN = 1;</code>
     */
    const UNKNOWN = 1;
    /**
     * Generated from protobuf enum <code>STORAGE_NOT_FOUND = 2;</code>
     */
    const STORAGE_NOT_FOUND = 2;
    /**
     * Generated from protobuf enum <code>STORAGE_ALREADY_EXISTS = 3;</code>
     */
    const STORAGE_ALREADY_EXISTS = 3;
    /**
     * Generated from protobuf enum <code>STORAGE_PERMISSIONDENIED = 4;</code>
     */
    const STORAGE_PERMISSIONDENIED = 4;
    /**
     * Generated from protobuf enum <code>CONTEXT_USER_REQUIRED = 5;</code>
     */
    const CONTEXT_USER_REQUIRED = 5;
    /**
     * Generated from protobuf enum <code>PATH_INVALID = 6;</code>
     */
    const PATH_INVALID = 6;
    /**
     * Generated from protobuf enum <code>PUBLIC_LINK_NOT_FOUND = 7;</code>
     */
    const PUBLIC_LINK_NOT_FOUND = 7;
    /**
     * Generated from protobuf enum <code>PUBLIC_LINK_INVALID_DATE = 8;</code>
     */
    const PUBLIC_LINK_INVALID_DATE = 8;
    /**
     * Generated from protobuf enum <code>STORAGE_NOT_SUPPORTED = 9;</code>
     */
    const STORAGE_NOT_SUPPORTED = 9;
    /**
     * Generated from protobuf enum <code>USER_NOT_FOUND = 10;</code>
     */
    const USER_NOT_FOUND = 10;
    /**
     * Generated from protobuf enum <code>TOKEN_INVALID = 11;</code>
     */
    const TOKEN_INVALID = 11;
}

