<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.UpdateLinkReq</code>
 */
class UpdateLinkReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token = 1;</code>
     */
    private $token = '';
    /**
     * Generated from protobuf field <code>bool update_password = 2;</code>
     */
    private $update_password = false;
    /**
     * Generated from protobuf field <code>string password = 3;</code>
     */
    private $password = '';
    /**
     * Generated from protobuf field <code>bool update_expiration = 4;</code>
     */
    private $update_expiration = false;
    /**
     * Generated from protobuf field <code>uint64 expiration = 5;</code>
     */
    private $expiration = 0;
    /**
     * Generated from protobuf field <code>bool read_only = 6;</code>
     */
    private $read_only = false;
    /**
     * Generated from protobuf field <code>bool update_read_only = 7;</code>
     */
    private $update_read_only = false;

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool update_password = 2;</code>
     * @return bool
     */
    public function getUpdatePassword()
    {
        return $this->update_password;
    }

    /**
     * Generated from protobuf field <code>bool update_password = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setUpdatePassword($var)
    {
        GPBUtil::checkBool($var);
        $this->update_password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool update_expiration = 4;</code>
     * @return bool
     */
    public function getUpdateExpiration()
    {
        return $this->update_expiration;
    }

    /**
     * Generated from protobuf field <code>bool update_expiration = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setUpdateExpiration($var)
    {
        GPBUtil::checkBool($var);
        $this->update_expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expiration = 5;</code>
     * @return int|string
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>uint64 expiration = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkUint64($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 6;</code>
     * @return bool
     */
    public function getReadOnly()
    {
        return $this->read_only;
    }

    /**
     * Generated from protobuf field <code>bool read_only = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setReadOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->read_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool update_read_only = 7;</code>
     * @return bool
     */
    public function getUpdateReadOnly()
    {
        return $this->update_read_only;
    }

    /**
     * Generated from protobuf field <code>bool update_read_only = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setUpdateReadOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->update_read_only = $var;

        return $this;
    }

}

