<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.WriteSummary</code>
 */
class WriteSummary extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 nchunks = 1;</code>
     */
    private $nchunks = 0;
    /**
     * Generated from protobuf field <code>uint64 total_size = 2;</code>
     */
    private $total_size = 0;

    public function __construct() {
        \GPBMetadata\Api\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 nchunks = 1;</code>
     * @return int|string
     */
    public function getNchunks()
    {
        return $this->nchunks;
    }

    /**
     * Generated from protobuf field <code>uint64 nchunks = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNchunks($var)
    {
        GPBUtil::checkUint64($var);
        $this->nchunks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total_size = 2;</code>
     * @return int|string
     */
    public function getTotalSize()
    {
        return $this->total_size;
    }

    /**
     * Generated from protobuf field <code>uint64 total_size = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->total_size = $var;

        return $this;
    }

}

